#name: Jar Deployment To Google Cloud Storage
#
##on:
##  push:
##    branches: [ "main" ]
##  pull_request:
##    branches: [ "main" ]
#
#on:
#  workflow_run:
#    workflows: ["maven.yml"]
#    types:
#      - completed
#
#jobs:
#  build:
#    runs-on: ubuntu-latest
#    permissions:
#      contents: 'read'
#      id-token: 'write'
#    steps:
#      - name: Checkout code
#        uses: actions/checkout@v4
#
#      - name: Authenticate with Google Cloud
#        uses: google-github-actions/auth@v2
#        with:
#          service_account_email: ${{ secrets.JAR_DEPLOYMENT_EMAIL }}
#          service_account_key: ${{ secrets.JAR_DEPLOYMENT_KEY }}
#          project_id: github-actions-jar-deployment
#
#      - name: Upload JAR file to Google Cloud Storage
#        uses: google-github-actions/upload-cloud-storage@v2
#        with:
#          path: '/home/runner/work/JabberPoint-SoftwareQuality/JabberPoint-SoftwareQuality/target/JabberPoint-SoftwareQuality-1.0-SNAPSHOT.jar'
#          destination: 'software-quality-jar/'
